In [43]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import seaborn as sns
import matplotlib.pyplot as plt

import pickle
import warnings
warnings.filterwarnings('ignore')

In [44]:
df = pd.read_csv(r"C:\Users\techno\OneDrive\Data Trained\Flip Robo (Batch 1836)\Car Price Prediction\Scraped Data\cardekhotry1.csv")

In [45]:
df

,Unnamed: 0,Brand,Model,Variant,Manufacturing Year,Fuel Type,Driver Kilometers,Number of Owners,Location,Car Price
0,0,Audi A6,35 TDI,Automatic,2015,Diesel,81817,2.0,Jaipur,1798900
1,1,Audi Q5,30 TDI quattro Premium,Automatic,2015,Diesel,61127,1.0,Jaipur,2948600
2,2,Datsun GO,T,Manual,2016,Petrol,45197,1.0,Delhi NCR,275000
3,3,Datsun GO Plus,Remix Limited Edition,Manual,2018,Petrol,64285,1.0,Delhi NCR,291000
4,4,Datsun RediGO,AMT 1.0 T Option,Automatic,2020,Petrol,3294,1.0,Bangalore,516000
...,...,...,...,...,...,...,...,...,...,...
11770,11770,Volvo Xc90 D5 Inscription,NaN,Automatic,2021,Diesel,10000,1.0,Delhi NCR,9300000
11771,11771,Volvo Xc90 D5 Inscription,NaN,Automatic,2021,Diesel,11000,1.0,Delhi NCR,9300000
11772,11772,Volvo Xc90 D5 Inscription Bsiv,NaN,Automatic,2018,Diesel,57000,2.0,Delhi NCR,5750000
11773,11773,Volvo XC90 D5 Inscription BSIV,NaN,Automatic,2016,Diesel,50000,1.0,Delhi NCR,4500000
11774,11774,Volvo Xc90 D5 Momentum Bsiv,NaN,Automatic,2018,Diesel,41000,1.0,Bangalore,6300000

In [46]:
#df.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'], inplace=True)

In [47]:
#model_list=['Honda Amaze', 'Honda Brio', 'Honda Br', 'Honda City', 'Honda Civic', 'Honda Cr', 'Honda Jazz', 'Honda Mobilio', 'Honda WR', 'Honda Wr', 'Hyundai Accent', 'Hyundai Alcazar', 'Hyundai Aura', 'Hyundai Creta', 'Hyundai Elantra', 'Hyundai Eon', 'Hyundai EON', 'Hyundai Getz', 'Hyundai Grand I10', 'Hyundai Grand i10', 'Hyundai I10', 'Hyundai i10', 'Hyundai I20', 'Hyundai i20', 'Hyundai Kona', 'Hyundai Santa', 'Hyundai Santro', 'Hyundai Sonata', 'Hyundai Tucson', 'Hyundai Venue', 'Hyundai Verna', 'Hyundai Xcent', 'Isuzu D', 'Isuzu Mu', 'ICML Extreme', 'Jaguar F', 'Jaguar Xe', 'Jaguar Xf', 'Jaguar Xj', 'Jeep Compass', 'Jeep Grand', 'Kia Carnival', 'Kia Seltos', 'Kia Sonet', 'Land Rover Discovery', 'Land Rover Freelander', 'Land Rover Range Rover', 'Mahindra Alturas', 'Mahindra Bolero', 'Mahindra E Verito', 'Mahindra E2o Plus', 'Mahindra Kuv 100', 'Mahindra KUV 100', 'Mahindra Logan', 'Mahindra Marazzo', 'Mahindra Nuvosport', 'Mahindra Quanto', 'Mahindra Renault Logan', 'Mahindra Scorpio', 'Mahindra Ssangyong Rexton', 'Mahindra Supro', 'Mahindra Thar', 'Mahindra Tuv 300', 'Mahindra Verito', 'Mahindra Xuv300', 'Mahindra XUV500', 'Mahindra XUV500', 'Mahindra Xylo', 'Maruti 800', 'Maruti A Star', 'Maruti Alto 800', 'Maruti Alto Green', 'Maruti Alto K10', 'Maruti Alto', 'Maruti A-star', 'Maruti Baleno', 'Maruti Celerio', 'Maruti Ciaz', 'Maruti Dzire', 'Maruti Eeco', 'Maruti Ertiga', 'Maruti Esteem', 'Maruti Estilo', 'Maruti Grand', 'Maruti Ignis', 'Maruti Omni', 'Maruti Ritz', 'Maruti S-Cross', 'Maruti S-Presso', 'Maruti S-presso', 'Maruti Swift Dzire', 'Maruti Swift', 'Maruti SX4 Green', 'Maruti Sx4 S Cross', 'Maruti Sx4', 'Maruti SX4', 'Maruti Vitara Brezza', 'Maruti Wagon R', 'Maruti XL6', 'Maruti Xl6', 'Maruti Zen Estilo', 'Maruti Zen', 'Maserati Ghibli', 'Mercedes-benz A Class', 'Mercedes-benz B Class', 'Mercedes-benz C-class', 'Mercedes-benz A-class', 'Mercedes-benz Cla 200', 'Mercedes-Benz CL-Class', 'Mercedes-benz Clk Class', 'Mercedes-benz Cls-class', 'Mercedes-benz E-class', 'Mercedes-benz Gla', 'Mercedes-benz Gla Class', 'Mercedes-benz Glc', 'Mercedes-benz Gl-class', 'Mercedes-benz Gle', 'Mercedes-benz Gls', 'Mercedes-benz M-class', 'Mercedes-benz R-class', 'Mercedes-benz S-class', 'Mercedes-benz V-class', 'Mg Astor', 'Mg Gloster Savvy', 'Mg Hector Hybrid Sharp', 'Mg Hector Plus Sharp', 'Mg Hector Sharp', 'Mg Hector Smart', 'Mg Zs']

In [48]:
#model_list=['Mahindra KUV100', 'Mahindra TUV 300', 'Mahindra XUV300', 'Mahindra Xuv500', 'Mercedes-benz Amg', 'Mercedes-Benz C-Class', 'Mercedes-benz Cla Urban', 'Mercedes-Benz E-Class', 'Mercedes-Benz M-Class', 'Mg Hector Plus Select', 'Mg Hector Style', 'Mg Hector Super', 'Mini 3 Door Cooper', 'Mini 5 Door Cooper', 'Mini Cooper Countryman Cooper', 'Mini Cooper', 'Mitsubishi Cedia', 'Mitsubishi Lancer', 'Mitsubishi Outlander', 'Mitsubishi Pajero', 'New Skoda Rapid', 'Nissan Evalia', 'Nissan Kicks', 'Nissan Magnite', 'Nissan Micra', 'Nissan Sunny', 'Nissan Teana', 'Nissan Terrano', 'Nissan X-trail', 'Porsche Boxster', 'Porsche Cayenne', 'Porsche Cayman', 'Porsche Macan', 'Porsche Panamera', 'Renault Captur Platine', 'Renault Duster', 'Renault Fluence', 'Renault Kiger', 'Renault KWID', 'Renault KWID', 'Renault Kwid 1.0', 'Renault KWID 1.0', 'Renault KWID Climber 1.0', 'Renault Kwid Climber 1.0', 'Renault Kwid', 'Renault KWID']

In [49]:
model_list = ['Renault Lodgy', 'Renault Pulse', 'Renault Scala', 'Renault Triber', 'Rolls-royce Ghost Series', 'Skoda Fabia', 'Skoda Kodiaq', 'Skoda Kushaq', 'Skoda Laura', 'Skoda New Laura', 'Skoda Octavia', 'Skoda Rapid', 'Skoda Superb', 'Skoda Yeti', 'Tata Altroz', 'Tata Aria Pleasure', 'Tata Bolt', 'Tata Harrier', 'Tata Hexa', 'Tata Indica', 'Tata Indigo', 'Tata Manza', 'Tata Nano', 'Tata New Safari', 'Tata Nexon', 'Tata Safari', 'Tata Sumo', 'Tata Tiago', 'Tata Tigor', 'Tata Winger Standard', 'Tata Xenon', 'Tata Zest', 'Toyota Alphard', 'Toyota Camry', 'Toyota Corolla Altis', 'Toyota Corolla','Toyota Etios Cross', 'Toyota Etios Liva', 'Toyota Etios', 'Toyota Fortuner', 'Toyota Glanza', 'Toyota Innova', 'Toyota Innova Crysta', 'Toyota Land Cruiser Prado', 'Toyota Land Cruiser', 'Toyota Prado', 'Toyota Qualis', 'Toyota Urban Cruiser', 'Toyota Yaris', 'Volkswagen Ameo', 'Volkswagen Beetle', 'Volkswagen Crosspolo', 'Volkswagen Jetta', 'Volkswagen Passat', 'Volkswagen Polo', 'Volkswagen Taigun', 'Volkswagen Vento', 'Volvo S 80', 'Volvo S60', 'Volvo S90', 'Volvo V40', 'Volvo V90', 'Volvo Xc 90', 'Volvo Xc40', 'Volvo Xc60', 'Volvo Xc90']

In [50]:
for model in model_list:
    for i in range(df.shape[0]):
        if model in df['Brand'].loc[i]:
            if pd.isna(df['Model'].loc[i]):
                df['Model'].loc[i] = df['Brand'].loc[i].split(model)[1][1:]
                df['Brand'].loc[i] = model

In [51]:
from pathlib import Path  
filepath = Path("C:/Users/techno/OneDrive/Data Trained/Flip Robo (Batch 1836)/Car Price Prediction/Scraped Data/cardekhotry2.csv")  
filepath.parent.mkdir(parents=True, exist_ok=True)  
df.to_csv(filepath)

In [53]:
df = pd.read_csv(r"C:\Users\techno\OneDrive\Data Trained\Flip Robo (Batch 1836)\Car Price Prediction\Scraped Data\Car Price Prediction.csv")

In [54]:
df

,Brand,Model,Variant,Manufacturing Year,Fuel Type,Driver Kilometers,Number of Owners,Location,Car Price
0,Audi A6,35 TDI,Automatic,2015,Diesel,81817,2.0,Jaipur,1798900
1,Audi Q5,30 TDI quattro Premium,Automatic,2015,Diesel,61127,1.0,Jaipur,2948600
2,Datsun GO,T,Manual,2016,Petrol,45197,1.0,Delhi NCR,275000
3,Datsun GO Plus,Remix Limited Edition,Manual,2018,Petrol,64285,1.0,Delhi NCR,291000
4,Datsun RediGO,AMT 1.0 T Option,Automatic,2020,Petrol,3294,1.0,Bangalore,516000
...,...,...,...,...,...,...,...,...,...
21558,Hyundai Verna,2011-2014 SX CRDi AT,AUTOMATIC,2013,DIESEL,75000,2.0,Pune,530000
21559,Honda Brio,1.2 S MT,MANUAL,2012,PETROL,58000,1.0,Pune,295000
21560,Volkswagen Vento,2013-2015 1.6 Highline,MANUAL,2014,PETROL,44000,1.0,Pune,500000
21561,Honda Amaze,VX i-VTEC,MANUAL,2015,PETROL,67000,1.0,Pune,575000
21562,Ssangyong Rexton,RX7,AUTOMATIC,2013,DIESEL,97000,2.0,Pune,675000

In [57]:
for i in range(df.shape[0]):
    if df['Brand'].loc[i][0:1] == ' ':
        df['Brand'].loc[i] = df['Brand'].loc[i][1:]

In [59]:
from pathlib import Path  
filepath = Path("C:/Users/techno/OneDrive/Data Trained/Flip Robo (Batch 1836)/Car Price Prediction/Scraped Data/carpriceprediction.csv")  
filepath.parent.mkdir(parents=True, exist_ok=True)  
df.to_csv(filepath)